version: '3'

services:
  mestre:
    build: ./mestre
    ports:
      - "8080:8080"
    depends_on:
      - escravo1
      - escravo2

  escravo1:
    build: ./escravo1
    ports:
      - "8081:8081"

  escravo2:
    build: ./escravo2
    ports:
      - "8082:8082"
